- hosts: terraform-ansible
  gather_facts: no
  tasks:
    - name: criando o arquivo
      ansible.builtin.copy:
        dest: /home/ubuntu/index.html
        content: <h1> Feito com terraform e ansible </h1>

    - name: criando o servidor web
      ansible.builtin.shell: "nohup busybox httpd -f -p 8080 &"