---
- hosts: all
  tasks:
    - name: criando o arquivo
        copy:
          dest: /home/ubuntu/index.html
          content: <h1> Feito com terraform e ansible </h1>
  
    - name: criando o servidor web
        shell: "nohup busybox httpd -f -p 8080 &"

  become: yes